### ISSUE TITLE
Twitter style "just now" is blank

### ISSUE THREAD

**Issue by jordanambra** [catamphetamine/javascript-time-ago#10]
I'm using react-time-ago, but since that's just passing styles to this library, I figured this would be an appropriate place to file this. I'm actually not sure it's a bug, but there's no value defined for the Twitter "just now" time, where time ago is < 1 minute.

If I look at the https://catamphetamine.github.io/react-time-ago/ page, right now it shows under the Recently category as blank space until you wait on the page for a minute, when it turns to 1m (in locale en).

I need to be able to say "now" or "just now" in my app. Is this a bug that should be fixed, or should I be handling this within my app?

**Comment by catamphetamine** [comment]
Well, yeah, I don't exactly know why did I do it this way.
Perhaps "now" felt a bit redundant to me.
E.g. in an instant messaging platform one could show time like `19:45` or like `3m` and if the latter then seeing "now", "now", "now" would create a bit of visual clutter while having those blank would perhaps make sense (at least for me).
Anyway, you can customize Twitter scale like this:

```js
export default {
  ...twitter,
  gradation: [{
    factor: 1,
    unit: 'now'
  }].concat(twitter.gradation)
}
```

Try that, perhaps it works (most likely).
