### ISSUE TITLE
Require cycle

### ISSUE THREAD

**Issue by maxschmeling** [catamphetamine/javascript-time-ago#14]
There is a require cycle between [JavascriptTimeAgo.js](https://github.com/catamphetamine/javascript-time-ago/blob/89f433944a830a812a3aa27eb1eb25a15b3adf5c/source/JavascriptTimeAgo.js) and [RelativeTimeFormat.js](https://github.com/catamphetamine/javascript-time-ago/blob/89f433944a830a812a3aa27eb1eb25a15b3adf5c/source/RelativeTimeFormat.js).

From xcode console:
> Require cycle: node_modules/javascript-time-ago/commonjs/JavascriptTimeAgo.js -> node_modules/javascript-time-ago/commonjs/RelativeTimeFormat.js -> node_modules/javascript-time-ago/commonjs/JavascriptTimeAgo.js
>
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

The `RelativeTimeFormat` class uses `JavascriptTimeAgo` here:
https://github.com/catamphetamine/javascript-time-ago/blob/89f433944a830a812a3aa27eb1eb25a15b3adf5c/source/RelativeTimeFormat.js#L196-L208

The cyclic import is mentioned in the comments of the `addLocale` function declaration:
> Due to the cyclic `import` dependency the one-liner won't work. RelativeTimeFormat.addLocale = JavascriptTimeAgo.addLocale

But I would think it should be relatively simple to extract a class that would allow the cycle to be removed.

I can't work on a PR today, but I'd be willing to in the near future if there is interest in having that warning removed.

**Comment by catamphetamine** [comment]
Released `javascript-time-ago@1.0.33`.
