### ISSUE TITLE
How to deal with the timestamp value ? 

### ISSUE THREAD

**Issue by KiranUppunda** [catamphetamine/javascript-time-ago#18]
As you can see here, we have 

```
const timeAgo = new TimeAgo('en-US')
timeAgo.format(Date.now() - 60 * 1000)
``` 
In my case I am getting the timestamp value. I tried subtracting the same value from Date.now(), but I am not getting the correct answer. 

Can anyone please help me, how I can proceed with the timestamp values? 

Thank you.

**Comment by catamphetamine** [comment]
It's not clear what's the issue.
Provide more details.

**Comment by KiranUppunda** [comment]
Okay, 
I am trying to implement time ago, so I found "javascript-time-ago" is one good approach. 

In all examples we are subtracting the seconds,  for example, 
`
const timeAgo = new TimeAgo('en-US')
timeAgo.format(Date.now() - 60 * 1000)
`
i.e., current date - <seconds> 

But in my case I am getting Epoch timestamp: 1558245012  like this.
If I directly subtract it from the current time, its giving the wrong answer. 

So please let me know how can I go ahead. 

Thank you.

**Comment by catamphetamine** [comment]
It's not clear what your issue is.

**Comment by catamphetamine** [comment]
Test timestamps with `new Date().getTime()`

**Comment by KiranUppunda** [comment]
Hi, Sorry for not being clear.

In simple words, if I want to get the times ago for an item with timestamp value, how can I proceed with 'javascript-time-ago'.

PS: I have cloned your repo and trying.
