### ISSUE TITLE
micro texts?

### ISSUE THREAD

**Issue by blacksmoke26** [catamphetamine/javascript-time-ago#20]
5 seconds => 5s
50 mins => 50min
3 months => 3m
1 year => 1y

3+ words are way too long.

**Comment by catamphetamine** [comment]
See "twitter" style.

**Comment by blacksmoke26** [comment]
```
timeAgo.format(Date.now() - 365 * 24 * 60 * 60 * 1000, 'twitter')
// "Mar 5, 2017"
```
Still too long.

**Comment by catamphetamine** [comment]
Well, then you'll have to create your own style with "tiny" `flavour` and custom `gradation` and `units`.
