### ISSUE TITLE
Mocked Date objects break module

### ISSUE THREAD

**Issue by nijk** [catamphetamine/javascript-time-ago#22]
When using this module in a project tested with [cypress.io](https://www.cypress.io/) and using the date mock method `cy.clock()` the function `getDateAndTimeBeingFormatted` throws this error: `Unsupported relative time formatter input`.

I believe this is because the check for a valid date is done using [this expression](https://github.com/catamphetamine/javascript-time-ago/blob/master/source/JavascriptTimeAgo.js#L352).

In my case the constructor is not the Date object but rather one determined by [lolex](https://github.com/sinonjs/lolex) which Cypress uses under the hood. From my research on this subject, it seems appropriate to test the date in a manner similar to [this popular SO post on the subject](https://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript)

**Comment by catamphetamine** [comment]
Hi.
I see.
I simplified it to just:

```js
// During testing via some testing libraries `Date`s aren't actually `Date`s.
// https://github.com/catamphetamine/javascript-time-ago/issues/22
function isMockedDate(object) {
	return typeof object === 'object' && typeof object.getTime === 'function'
}
```

Released `javascript-time-ago@2.0.2`.
