### ISSUE TITLE
How is this different than TimeAgo.org?

### ISSUE THREAD

**Issue by tryhardest** [catamphetamine/javascript-time-ago#29]
Hi, we just finished migrating out jQuery from our codebase and we use timeago.js so now it makes sense to use timeago.org the 2kb lib without jQuery dependency. 

Then saw this library. Super interesting and I wonder if there are any reasons why this might be a better or uniquely different lib that that? Tnx

**Comment by catamphetamine** [comment]
Hi.
I didn't use `timeago.js`.
If it's just `2kB` then I guess use that unless it doesn't lack some features the project requires.
