### ISSUE TITLE
Format on Twitter style returns undefined on React Native/Android

### ISSUE THREAD

**Issue by oferRounds** [catamphetamine/javascript-time-ago#35]
On debug mode – works great. But on non-debug mode (different Javascript engine), format returns undefined. Any idea?

I would guess it might have to do with the Intl dependency, but in that case, wouldn’t it fall back to the default format?
In addition, default format does work

**Comment by oferRounds** [comment]
Timestamp example: `2020-05-03T20:21:54`

**Comment by catamphetamine** [comment]
Hmm, no idea, haven't worked with mobile apps.

**Comment by oferRounds** [comment]
Got you, thanks!
