### ISSUE TITLE
[React] React-Natitve support

### ISSUE THREAD

**Issue by KDederichs** [catamphetamine/javascript-time-ago#39]
Hey, since it's easier to just comment here than on the gitlab page I'll just drop the message here:
I tried using the React version on react-native but sadly it crashes due to the missing <time> tag.

Would it maybe be possible to maybe add either a wrapperComponent prop for it or maybe a prop toggles passing the result string to the wrapperComenponent directly?

Best regards,

**Comment by catamphetamine** [comment]
Added `component` property in `react-time-ago@6.2.1`.
https://gitlab.com/catamphetamine/react-time-ago#react-native
