### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by pablovisual** [catamphetamine/javascript-time-ago#42]
on return formatters[locale].dayMonthYear.format(getDate(value)), so im using firestore timestamp for the date, it works to display it fine but when adding something to the database in firestore it gives that error, I'm assuming it because the data is inserting first the time so it doesn't show post that I create. So was wondering how to still use javascript time ago with twitter style if I'm creating the post?

**Comment by catamphetamine** [comment]
What

**Comment by catamphetamine** [comment]
You're making no sense.

**Comment by pablovisual** [comment]
sorry, should have explained a bit more. So I'm using firestore to create posts with timestamps, timestamp: firebase.firestore.FieldValue.serverTimestamp(), this function creates the time and date on wherever the user is in the world. And I'm using this const time = timeAgo.format(new Date(timestamp?.toDate().toUTCString()), "twitter"). I create a post, goes into the firestore database then should output with everything and the date formatted like twitters. It works when i use mini; i consoled logged it and the new post that i added, the time says invalid time but no crash error, but when i set it to twitter style it gives range error: invaled time value. does the time value need to be a sort of int in order for twitter style to work properly?

**Comment by catamphetamine** [comment]
This package transforms a `Date` into a `string`.
It's irrelevant how someone stores dates or reads dates.
It's none of this package's concern.
