### ISSUE TITLE
New locale pt-BR

### ISSUE THREAD

**Issue by victorbiasibetti** [catamphetamine/javascript-time-ago#44]
Hello 

I liked the repository, but don't have a locale pt-BR

You interesting about new PR's with locale pt-BR?
I'm think gonna programming this issue :)

**Comment by catamphetamine** [comment]
Hello.

CLDR doesn't provide `pt-BR` locale data so we don't have it too.
I suppose they did have their reason not to include `pt-BR` in the list.
Use the usual `pt` then.

![image](https://user-images.githubusercontent.com/477167/117724795-f40fb380-b1ec-11eb-9d90-ef78ab748461.png)

**Comment by victorbiasibetti** [comment]
hmm, ok
but in branch master on `locale-more-style` don't have a `pt` file

**Comment by catamphetamine** [comment]
> but in branch master on `locale-more-style` don't have a `pt` file

Then you could add one

**Comment by victorbiasibetti** [comment]
> Then you could add one

Ok, i will do

**Comment by yeikel** [comment]
@victorbiasibetti you can fork the repository and then send the PR here

**Comment by victorbiasibetti** [comment]
@yeikel @catamphetamine the PR is https://github.com/catamphetamine/javascript-time-ago/pull/45

**Comment by catamphetamine** [comment]
@victorbiasibetti Thanks, published `javascript-time-ago@2.3.5`
