### ISSUE TITLE
Using this with Next JS - without dynamic import?

### ISSUE THREAD

**Issue by siliconjungle** [catamphetamine/javascript-time-ago#46]
Hey everyone, is there a solution to using this with Next JS on the backend?

**Comment by catamphetamine** [comment]
What's the issue

**Comment by siliconjungle** [comment]
Importing this: `import TimeAgo from 'javascript-time-ago/modules/TimeAgo';` ends up producing the following error: `SyntaxError: Cannot use import statement outside a module`.

**Comment by catamphetamine** [comment]
You shouldn't import anything like that
