### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by cherealnice** [catamphetamine/javascript-time-ago#5]
I was hoping to use this library, but I would need support for more languages.  Is there something in the pipeline? Is there a way to pull in another library to translate to other languages that aren't in the locales?  Thanks!

**Comment by catamphetamine** [comment]
There is
https://github.com/catamphetamine/javascript-time-ago#localization

**Comment by cherealnice** [comment]
Awesome thanks @catamphetamine
