### ISSUE TITLE
Mongoose timastamps not supported

### ISSUE THREAD

**Issue by oussamabouchikhi** [catamphetamine/javascript-time-ago#51]
I am trying to format timastamps using Mongoose createdAt field and I get an error.
I am using React and I wrote the following code
```javascript
import TimeAgo from 'javascript-time-ago'
import fr from 'javascript-time-ago/locale/fr'
TimeAgo.addDefaultLocale(fr);
const timeAgo = new TimeAgo('fr-FR');
```
```html
<span className="block text-xs text-right">{timeAgo.format(message.createdAt)}</span>
```
Then I get this error
`Error: Unsupported relative time formatter input: string, 2021-06-17T09:44:51.703Z`

**Comment by catamphetamine** [comment]
Well, you're passing a `String`.
Pass something like `new Date(message.createdAt)`.
