### ISSUE TITLE
TimeAgo.addDefaultLocale() can only be called once...

### ISSUE THREAD

**Issue by rcb4t2** [catamphetamine/javascript-time-ago#52]
In a React (Native) environment, when developing and using fast refresh with code changes, the addDefaultLocale method gets called again. It helps to put this initialization at the top-level App.js, but any time that file is edited TimeAgo throws an error

[javascript-time-ago] `TimeAgo.addDefaultLocale()` can only be called once. To add other locales, use `TimeAgo.addLocale()`.

Suggested fix: 
- add a flag on the TimeAgo object to indicate whether the default locale has been set
- OR let getDefaultLocale() return undefined (or other falsey value) when addDefaultLocale has not been called yet (currently returns 'en')
- OR let addDefaultLocale print to console or otherwise fail more gracefully when called more than once. Could call setDefaultLocale and print a warning?

Is there another way to initialize TimeAgo without this problem? I've tried several permutations of calling addDefaultLocale in exported files or setting isReady flags and the fast refresh always wipes it out and throws the error

The module is great so far but I'm nervous to use it in production until I settle this initialization issue

Thanks!

**Comment by catamphetamine** [comment]
Hi.
Published `javascript-time-ago@2.3.8` that doesn't throw: instead it just errors to the console.

**Comment by rcb4t2** [comment]
Hey @catamphetamine I didn't see this reply until now, but thank you for updating it!

**Comment by neongreen** [comment]
I switched to

```typescript
TimeAgo.setDefaultLocale(en.locale)
TimeAgo.addLocale(en)
```

so that I would never get a warning.
