### ISSUE TITLE
[QUESTION] Format month

### ISSUE THREAD

**Issue by lluisemper** [catamphetamine/javascript-time-ago#55]
Going over 31 days will still show days, adding a label array did nothing with ['custom', 'short', 'twitter']

I have a custom style like so:

`
const customLabels = {
   now: {
      past: {
         one: "now",
         other: "now",
      },
   },
   second: {
      past: {
         one: "now",
         other: "now",
      },
   },
   minute: {
      past: {
         one: "{0}m",
         other: "{0}m",
      },
   },
   hour: {
      past: {
         one: "{0}h",
         other: "{0}h",
      },
   },
   day: {
      past: {
         one: "{0}d",
         other: "{0}d",
      },
   },
};
`
As you can see I have not defined the months and I would like to use the twitter format, how can I do so? I do not know how to define it like 31 Aug, or should I just use javascript to change the label used?

**Comment by catamphetamine** [comment]
> As you can see I have not defined the months and I would like to use the twitter format

Then months won't be used, that's true.

> how can I do so?

It doesn't seem like any specific configuration would be required.

> I do not know how to define it like 31 Aug, or should I just use javascript to change the label used?

What?

**Comment by lluisemper** [comment]
Sorry, what I mean, is there a way to express <day> <Short Month> if the month is not specified in the custom style?

**Comment by catamphetamine** [comment]
There's no such way.

**Comment by catamphetamine** [comment]
> Going over 31 days will still show days, adding a label array did nothing with ['custom', 'short', 'twitter']

What?
Twitter is supposed to show days.

**Comment by lluisemper** [comment]
Is it like `timeStyle="twitter"Aug 30` ?

**Comment by catamphetamine** [comment]
> Is it like `timeStyle="twitter"Aug 30` ?

What?

**Comment by lluisemper** [comment]
Oh silly of me!! I do apologize, I was linked to your custom styling from another repo... (react-time-ago)

**Comment by catamphetamine** [comment]
> Oh silly of me!! I do apologize, I was linked to your custom styling from another repo... (react-time-ago)

That is fine, I wrote that one too.

**Comment by catamphetamine** [comment]
I guess this one can be closed if there's no issue.
If you think there's an issue then you can reopen it.
