### ISSUE TITLE
minute is defined twice in convenient gradation

### ISSUE THREAD

**Issue by vinayr** [catamphetamine/javascript-time-ago#6]
https://github.com/catamphetamine/javascript-time-ago/blob/master/source/gradation/convenient.js#L40-L50

This explains why I see updates every 5 minutes instead of every minute (https://github.com/catamphetamine/react-time-ago/issues/5)

Is this intentional?

**Comment by catamphetamine** [comment]
Oh, you actually did go that far.
Ok...

```js
	{
		unit: 'second',
		factor: 1,
		threshold: 1,
		threshold_for_now: 45
	},
	{
		unit: 'minute',
		factor: 60,
		threshold: 45
	},
	{
		unit: 'minute',
		factor: 60,
		threshold: 2.5 * 60,
		granularity: 5
	},
```

So, here's the scale (if without now):

1 - 1 second
2 - 2 seconds
...
44 - 44 seconds
45 - a minute
46 - a minute
...
59 - a minute
60 - a minute
89 - a minute
90 - 2 minutes
...
149 - 2 minutes
150 - 5 minutes
151 - 5 minutes

Use "canonical" scale if you want precise minutes (2, 3, 4, 5)
If you think that you're observing a bug then you can post more info on it.

**Comment by catamphetamine** [comment]
gradation steps can have repeated units (it's more flexible this way)

**Comment by vinayr** [comment]
got it...thanks
