### ISSUE TITLE
How to use english.tiny

### ISSUE THREAD

**Issue by lukakerr** [catamphetamine/javascript-time-ago#8]
I've read the docs and see theres a time style of english.tiny:

```javascript
english.tiny  // '1s', '2m', '3h', '4d', …
```

How do you use this style? I've tried:

```javascript
import TimeAgo from 'javascript-time-ago';
import english from 'javascript-time-ago/locale/en';

TimeAgo.locale(english);
const timeAgo = new TimeAgo('en-US');

timeAgo.format(Date.now() - 60 * 1000, 'tiny');
``` 

but it isn't working. It just gives a long date such as: `2 hours ago`.

**Comment by lukakerr** [comment]
Nevermind, got it. You need to pass an object: 

```javascript
timeAgo.format(Date.now() - 60 * 1000, { flavour: 'tiny' });
```

**Comment by catamphetamine** [comment]
Yeah, I updated the readme a bit describing `style`
https://github.com/catamphetamine/javascript-time-ago#customization

**Comment by catamphetamine** [comment]
Rewrote the customization section again.
